name: Build & Test

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml 4.11.1
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.11.1

      - name: Set git user
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions-bot@users.noreply.github.com

      - name: Build & Test
        run: opam exec dune build @install @runtest
